trigger:
    - master

steps:

- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'dockerRegistryServiceConnection1'
    repository: 'bragalund/bragalund-public'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'

- task: Docker@2
  displayName: Logout of ACR
  inputs:
    command: logout
    containerRegistry: 'dockerRegistryServiceConnection1'

