trigger:
    - master

steps:

- task: Docker@2
  displayName: Build and Push Frontend
  inputs:
    containerRegistry: 'dockerRegistryServiceConnection1'
    repository: 'bragalund/bragalund-public:frontend'
    command: 'buildAndPush'
    Dockerfile: 'frontend/Dockerfile'
    
- task: Docker@2
  displayName: Build and Push Backend
  inputs:
    containerRegistry: 'dockerRegistryServiceConnection1'
    repository: 'bragalund/bragalund-public:backend'
    command: 'buildAndPush'
    Dockerfile: 'backend/Dockerfile'

- task: Docker@2
  displayName: Logout of ACR
  inputs:
    command: logout
    containerRegistry: 'dockerRegistryServiceConnection1'

